name: Push to Digital Ocean

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: run on digital ocean sever
      uses: appleboy/ssh-action@master
      with:
        host: 157.245.220.137
        username: root
        password: rowboats
        script: "sudo sh ~/telestrations/run.sh" 
